CREATE TABLE Course (
  dept VARCHAR(255),
	code VARCHAR(255),
	description VARCHAR(255),
	instructor VARCHAR (255)
);

CREATE TABLE Student (
	firstName VARCHAR(255),
	lastName VARCHAR(255),
	grad_year INTEGER,
	dept VARCHAR(255),
	course_taken VARCHAR(255)
);

INSERT INTO Course VALUES
('CSE', '3', 'Fluency/Information Technology', 'STAFF'),
('CSE', '8A', 'Intro/Computer Science: Java (I)', 'Politz'),
('CSE', '8B', 'Intro/Computer Sci. Java (II)', 'Alvarado'),
('CSE', '11', 'Intr/Computer Sci&Obj-Ori:Java', 'STAFF'),
('CSE', '12', 'Basic Data Struct & OO Design', 'Gillespie'),
('CSE', '15L', 'Software Tools and Techniques Lab', 'Gillespie'),
('CSE', '20', 'Intro/Discrete Mathematics', 'Minnes Kemp'),
('CSE', '21', 'Math/Algorithm&Systems Analys', 'STAFF'),
('CSE', '30', 'Computer Organiz&Systms Progrm', 'Porter, L.'),
('CSE', '95', 'Tutor Apprentice', 'Gillespie'),
('CSE', '100', 'Advanced Data Structures', 'Moshiri'),
('CSE', '101', 'Design & Analysis of Algorithm', 'Kane'),
('CSE', '105', 'Theory of Computation', 'STAFF'),
('CSE', '110', 'Software Engineering', 'STAFF'),
('CSE', '120', 'Princ/Computer Operating Systm', 'Pasquale'),
('CSE', '123', 'Computer Networks', 'Snoeren'),
('CSE', '127', 'Intro to Computer Security', 'Heninger'),
('CSE', '130', 'Progrmng Lang:Princpl&Paradigm', 'Jhala'),
('CSE', '132A', 'NO COURSE DESCRIPTION', 'Vianu'),
('CSE', '134B', 'Web Client Languages', 'STAFF'),
('CSE', '140', 'Component&Desgn Tech/Digtl Sys', 'Rosing'),
('CSE', '140L', 'Digital Systems Laboratory', 'STAFF'),
('CSE', '141', 'Intro/Computer Architecture', 'Zhao'),
('CSE', '141L', 'Project/Computer Architecture', 'STAFF'),
('CSE', '151A', 'Intro to Machine Learning', 'Chaudhuri'),
('ECE', '5', 'Experience ECE: Making, Breaking, Hacking Stuff', 'Morris'),
('ECE', '15', 'Engineering Computation', 'Schurgers'),
('ECE', '16', 'Rapid Hardware and Software Design', 'Wang'),
('ECE', '25', 'Introduction to Digital Design', 'Dey'),
('ECE', '30', 'Introduction to Computer Engineering', 'Mirarab'),
('ECE', '35', 'Introduction to Analog Design', 'Schurgers'),
('ECE', '45', 'Circuits & Systems', 'Zeger'),
('ECE', '65', 'Components & Circuits Laboratory', 'Baghdadchi'),
('ECE', '101', 'Linear Systems Fundamentals', 'Baghdadchi'),
('ECE', '102', 'Introduction to Active Circuit Design', 'Le'),
('ECE', '103', 'Fundamentals of Devices & Materials', 'Taur'),
('ECE', '107', 'Electromagnetism', 'Lomakin'),
('ECE', '109', 'Engineering Probability & Statistics', 'Vardy'),
('ECE', '111', 'Advanced Digital Design Project', 'Karna'),
('ECE', '121B', 'Energy Conversion', 'Esmaili'),
('ECE', '125A', 'Power Electronics I', 'Le'),
('ECE', '128B', 'Power Grid Modernization', 'Abi-Samra'),
('ECE', '134', 'Electronic Materials Science of Integrated Circuits', 'Ng'),
('ECE', '135B', 'Electronic Devices', 'Dayeh'),
('ECE', '140A', 'The Art of Product Engineering I', 'Gessner & Khoshabeh'),
('ECE', '141A', 'Software Foundations I', 'Gessner'),
('ECE', '143', 'Programming for Data Analysis', 'Unpingco'),
('ECE', '144', 'LabView Programming', 'Phan');

INSERT INTO Student VALUES
('Craig', 'Day', 2023, 'CSE', '8B'),
('Craig', 'Day', 2023, 'CSE', '11'),
('Craig', 'Day', 2023, 'CSE', '12'),
('Craig', 'Day', 2023, 'CSE', '15L'),
('Craig', 'Day', 2023, 'CSE', '20'),
('Craig', 'Day', 2023, 'CSE', '21'),
('Mildred', 'Stevenson', 2024, 'ECE', '5'),
('Mildred', 'Stevenson', 2024, 'ECE', '15'),
('Francis', 'Hart', 2024, 'CSE', '8A'),
('Francis', 'Hart', 2024, 'CSE', '8B'),
('Roger', 'Lawson', 2024, 'CSE', '8A'),
('Bobbie', 'Todd', 2023, 'CSE', '8A'),
('Bobbie', 'Todd', 2023, 'CSE', '8B'),
('Bobbie', 'Todd', 2023, 'CSE', '11'),
('Bobbie', 'Todd', 2023, 'ECE', '15'),
('Bobbie', 'Todd', 2023, 'ECE', '16'),
('Bobbie', 'Todd', 2023, 'ECE', '17'),
('Bobbie', 'Todd', 2023, 'ECE', '25'),
('Bobbie', 'Todd', 2023, 'ECE', '30'),
('Samantha', 'Anderson', 2022, 'CSE', '8B'),
('Samantha', 'Anderson', 2022, 'CSE', '11'),
('Samantha', 'Anderson', 2022, 'CSE', '12'),
('Samantha', 'Anderson', 2022, 'CSE', '15L'),
('Samantha', 'Anderson', 2022, 'CSE', '20'),
('Samantha', 'Anderson', 2022, 'CSE', '21'),
('Samantha', 'Anderson', 2022, 'CSE', '30'),
('Samantha', 'Anderson', 2022, 'CSE', '100'),
('Samantha', 'Anderson', 2022, 'CSE', '101'),
('Samantha', 'Anderson', 2022, 'CSE', '105'),
('Samantha', 'Anderson', 2022, 'CSE', '110'),
('Samantha', 'Anderson', 2022, 'CSE', '120'),
('Samantha', 'Anderson', 2022, 'CSE', '140'),
('Samantha', 'Anderson', 2022, 'CSE', '140L');